In [16]:
import kNN
from numpy import *
group, labels = kNN.createDataSet()
data = numpy.array([[1,2,3],
        [3,4,5]])
c = data**2
print c
print '---------'
print c.sum(axis=0)
print '---------'
print c.sum(axis=1)

[[ 1  4  9]
 [ 9 16 25]]
---------
[10 20 34]
---------
[14 50]
